"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"light13's vim config
"2010/12/16 21:56:07
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

set backupcopy=yes
let g:nerd_font = 1

source ~/.vim/config/bundle.vim " 先装插件，保证自定义配置优先级
source ~/.vim/config/color.vim
source ~/.vim/config/general.vim
source ~/.vim/config/interface.vim
source ~/.vim/config/shortcuts.vim
runtime! config/plugin/**/*.vim

" vim:set expandtab shiftwidth=4 tabstop=4:
