"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"light13's vim config
"2010/12/16 21:56:07
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

set backupcopy=yes

"let g:dev_computer = 1

runtime! config/**/*.vim

" ~/.vim/config
"
" 其它人可能不习惯的设置恢复
" set nolist
" iunmap jk

" vim: shiftwidth=4
