# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="juanghurtado"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=~/.zsh

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git
         thefuck
         zsh-syntax-highlighting
         z
         httpie
         history
         pip
         npm
         supervisor
         extract
         cp
         tmux
         virtualenv
         rand-quote
         zsh-autosuggestions)

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"


# add by lightxue

# 自定义命令
# 查询IP地址
i() curl https://ip.cn/$1

# 别名

funcion save_alias() {
    local cmd=$1
    local dep_cmd=$2
    local alias_cmd=$2
    if [ -n "$3" ]; then
        alias_cmd="$3"
    fi
    if type $dep_cmd > /dev/null; then
        alias $cmd="$alias_cmd"
    fi
}

alias vi='vim'
alias more='less'
#alias tmux='tmux -2'
alias wl='wc -l'
alias tf='tail -f'
alias cnter='sort | uniq -c | sort -nr'

if [ $(uname -s) = 'Linux' ]; then
    alias mk="make -j$(grep --count processor /proc/cpuinfo)"
else
    alias mk="make"
fi
alias mc="make clean"
alias mck="mc && mk"
alias mi="make install"
alias agi="sudo apt-get install -y"
alias gbk='iconv -f gbk -t utf8'

save_alias cat bat 'bat --style plain --paging never'
save_alias pping prettyping
save_alias l exa 'exa --long -a'
save_alias ll exa 'exa --long'
save_alias j z 'z' # cd, same functionality as j in autojump

# 设置默认编辑器
export VISUAL=vim
export EDITOR=vim

# export LC_ALL=zh_CN.UTF-8

# 设置PATH
export PATH="$PATH:/usr/sbin:/usr/local/sbin"
bin="$HOME/.dotfiles.bin"
case `uname -s` in
    Linux*) export PATH="$PATH:$bin/linux" ;;
    Darwin*) export PATH="$PATH:$bin/mac"  ;;
esac

function src_file() {
    [ -f $1 ] && source $1
}

src_file ~/.zsh-custom

# fzf
src_file ~/.fzf.zsh

if [ "$TERM" = "xterm" ]; then
    export TERM=xterm-256color
fi
