# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# 环境变量
# 语言
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
# 设置默认编辑器
export VISUAL=nvim
export EDITOR=nvim
# 设置PATH
export GOPATH="$HOME/.local/go"
export PATH="$HOME/.local/bin:$GOPATH/bin:/opt/homebrew/bin:$PATH:/usr/sbin:/usr/local/sbin"
# 设置终端类型
if [ "$TERM" = "xterm" ]; then
    export TERM=xterm-256color
fi

source ~/.zplug/init.zsh
# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="juanghurtado"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=~/.zsh

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.

zplug 'zplug/zplug', hook-build:'zplug --self-manage'
zplug "plugins/git", from:oh-my-zsh
zplug "plugins/aliases", from:oh-my-zsh
zplug "plugins/macos", from:oh-my-zsh
zplug "plugins/sudo", from:oh-my-zsh
zplug "plugins/command-not-found", from:oh-my-zsh
zplug "plugins/colorize", from:oh-my-zsh
zplug "plugins/asdf", from:oh-my-zsh
zplug "plugins/httpie", from:oh-my-zsh
zplug "plugins/history", from:oh-my-zsh
zplug "plugins/pip", from:oh-my-zsh
zplug "plugins/npm", from:oh-my-zsh
zplug "plugins/supervisor", from:oh-my-zsh
zplug "plugins/extract", from:oh-my-zsh
zplug "plugins/cp", from:oh-my-zsh
zplug "plugins/tmux", from:oh-my-zsh
zplug "plugins/docker", from:oh-my-zsh
zplug "plugins/docker-compose", from:oh-my-zsh
zplug "plugins/virtualenv", from:oh-my-zsh
zplug "plugins/rand-quote", from:oh-my-zsh
zplug "plugins/gitignore", from:oh-my-zsh
zplug "plugins/web-search", from:oh-my-zsh
zplug "plugins/colored-man-pages", from:oh-my-zsh
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-autosuggestions"
# zplug "marlonrichert/zsh-autocomplete"
zplug "zsh-users/zsh-syntax-highlighting"
zplug "changyuheng/zsh-interactive-cd"
zplug "BlaineEXE/zsh-cmd-status"
zplug "romkatv/powerlevel10k", as:theme, depth:1
zplug "MichaelAquilina/zsh-you-should-use"
# zplug "jeffreytse/zsh-vi-mode"

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

function src_file() {
    [ -f $1 ] && source $1
}

src_file ~/.fzf.zsh
src_file ~/.p10k.zsh # To customize prompt, run `p10k configure`

eval "$(zoxide init zsh --cmd j)"

zvm_config() {
  ZVM_VI_ESCAPE_BINDKEY=jk
  # Always starting with insert mode for each command line
  ZVM_LINE_INIT_MODE=$ZVM_MODE_INSERT
  bind -m vi-command 'Control-l: clear-screen'
  bind -m vi-insert 'Control-l: clear-screen'
  bind -m vi-command 'Control-d: exit_zsh'
  bind -m vi-insert 'Control-d: exit_zsh'
}

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load
